title: "P2.0 Occupata"
description: "Sito ufficiale dell'aula P2.0 Occupata dell'UNICAL"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  p2occupata

locale: it
theme: minima
plugins:
  - jekyll-feed

collections:
  events:
    output: true

sass:
  sass_dir: _sass

default_header_image: "/assets/images/header.jpg"

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/