title: "P2.0 Occupata"
description: "Sito ufficiale dell'aula P2.0 Occupata dell'UNICAL"
url: "https://p2occupata.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/p2occupata" # the subpath of your site, e.g. /blog
github_username:  p2occupata

locale: it
date_locale: it

theme: minima

plugins:
  - jekyll-feed
  - jekyll-date-localization
  - jekyll-toc

future: true
collections:
  events:
    output: true
    permalink: /eventi/:title/

toc:
  min_level: 1
  max_level: 6

sass:
  sass_dir: _sass

default_header_image: "/assets/images/header.jpg"

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/